// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Formula$Formform from "../src/core/form/Formula.bs.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

var fml_samples = [
  {
    fml: "",
    tks: /* [] */0
  },
  {
    fml: " )( )  ( ",
    tks: {
      hd: {
        TAG: /* Mark */0,
        _0: /* Close */1
      },
      tl: {
        hd: {
          TAG: /* Mark */0,
          _0: /* Open */0
        },
        tl: {
          hd: {
            TAG: /* Mark */0,
            _0: /* Close */1
          },
          tl: {
            hd: {
              TAG: /* Mark */0,
              _0: /* Open */0
            },
            tl: /* [] */0
          }
        }
      }
    }
  },
  {
    fml: "(N((U )I)  )M",
    tks: {
      hd: {
        TAG: /* Mark */0,
        _0: /* Open */0
      },
      tl: {
        hd: {
          TAG: /* Const */3,
          _0: /* N */0
        },
        tl: {
          hd: {
            TAG: /* Mark */0,
            _0: /* Open */0
          },
          tl: {
            hd: {
              TAG: /* Mark */0,
              _0: /* Open */0
            },
            tl: {
              hd: {
                TAG: /* Const */3,
                _0: /* U */1
              },
              tl: {
                hd: {
                  TAG: /* Mark */0,
                  _0: /* Close */1
                },
                tl: {
                  hd: {
                    TAG: /* Const */3,
                    _0: /* I */2
                  },
                  tl: {
                    hd: {
                      TAG: /* Mark */0,
                      _0: /* Close */1
                    },
                    tl: {
                      hd: {
                        TAG: /* Mark */0,
                        _0: /* Close */1
                      },
                      tl: {
                        hd: {
                          TAG: /* Const */3,
                          _0: /* M */3
                        },
                        tl: /* [] */0
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  {
    fml: "\"a\"\" süßer_apfel b\"(/b_1 n_+2 /\"42/4\")\")\"",
    tks: {
      hd: {
        TAG: /* VarStr */6,
        _0: {
          TAG: /* Label */0,
          _0: "a"
        }
      },
      tl: {
        hd: {
          TAG: /* VarStr */6,
          _0: {
            TAG: /* LabelSub */1,
            lbl: " süßer",
            sub: "apfel b"
          }
        },
        tl: {
          hd: {
            TAG: /* Mark */0,
            _0: /* Open */0
          },
          tl: {
            hd: {
              TAG: /* Uncl */7,
              _0: {
                TAG: /* LabelSub */1,
                lbl: "b",
                sub: "1 n_+2 "
              }
            },
            tl: {
              hd: {
                TAG: /* VarStr */6,
                _0: {
                  TAG: /* Label */0,
                  _0: "42/4"
                }
              },
              tl: {
                hd: {
                  TAG: /* Mark */0,
                  _0: /* Close */1
                },
                tl: {
                  hd: {
                    TAG: /* VarStr */6,
                    _0: {
                      TAG: /* Label */0,
                      _0: ")"
                    }
                  },
                  tl: /* [] */0
                }
              }
            }
          }
        }
      }
    }
  },
  {
    fml: "\"_\"/a_/\"_a\"",
    tks: {
      hd: {
        TAG: /* VarStr */6,
        _0: {
          TAG: /* Label */0,
          _0: "_"
        }
      },
      tl: {
        hd: {
          TAG: /* Uncl */7,
          _0: {
            TAG: /* Label */0,
            _0: "a_"
          }
        },
        tl: {
          hd: {
            TAG: /* VarStr */6,
            _0: {
              TAG: /* Label */0,
              _0: "_a"
            }
          },
          tl: /* [] */0
        }
      }
    }
  }
];

var fml_invalid = [
  {
    fml: "\"",
    exn: "Closing '\"' is missing!"
  },
  {
    fml: "/",
    exn: "Closing '/' is missing!"
  },
  {
    fml: "\"a\"\"",
    exn: "Closing '\"' is missing!"
  },
  {
    fml: "/\"/a/",
    exn: "Closing '/' is missing!"
  },
  {
    fml: "//a\"/",
    exn: "Label should not be empty!"
  },
  {
    fml: "\"\"\"",
    exn: "Label should not be empty!"
  }
];

Zora.test("Testing Lexer.scan", (function (t) {
        fml_samples.forEach(function (sample) {
              t.test("given a formula '" + sample.fml + "'", (function (t) {
                      var input = sample.fml;
                      var actual = Formula$Formform.Lexer.scan(input);
                      var expected = sample.tks;
                      t.equal(actual, expected, "should be a token stream");
                      
                    }));
              
            });
        fml_invalid.forEach(function (sample) {
              t.test("given an invalid formula '" + sample.fml + "'", (function (t) {
                      var input = sample.fml;
                      var expected = sample.exn;
                      var val;
                      try {
                        val = Formula$Formform.Lexer.scan(input);
                      }
                      catch (raw_exn){
                        var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
                        if (exn.RE_EXN_ID === Formula$Formform.Lexer.LexError) {
                          var msg = exn.msg;
                          t.equal(msg, expected, "should be \"" + expected + "\", but was \"" + msg + "\"");
                          return ;
                        }
                        throw exn;
                      }
                      t.fail("expected error, but scan successful");
                      
                    }));
              
            });
        
      }));

export {
  fml_samples ,
  fml_invalid ,
  
}
/*  Not a pure module */
