// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "@dusty-phillips/rescript-zora/src/Zora.bs.js";
import * as Zora$1 from "zora";
import * as Helper$Formform from "../src/utils/Helper.bs.js";

var nBase_samples_valid = [
  [
    "1330",
    4,
    124
  ],
  [
    "3101301",
    4,
    13425
  ],
  [
    "48946",
    10,
    48946
  ],
  [
    "0",
    9,
    0
  ],
  [
    "1001000011001101001100011000110010101000111",
    2,
    1770808647
  ]
];

Zora$1.test("Testing intFromStrWithRadix", (function (t) {
        nBase_samples_valid.forEach(function (param) {
              var expected = param[2];
              var base = param[1];
              var input = param[0];
              t.test("given a numebr " + input + " and base " + String(base), (function (t) {
                      var actual = Helper$Formform.intFromStrWithRadix(base, input);
                      return Zora.optionSome(t, actual, (function (t, result) {
                                    t.equal(result, expected, "should be a correct number");
                                    
                                  }));
                    }));
              
            });
        
      }));

export {
  nBase_samples_valid ,
  
}
/*  Not a pure module */
