// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as DNA$Formform from "../src/core/calc/DNA.bs.js";
import * as Calc$Formform from "../src/core/calc/Calc.bs.js";
import * as Value$Formform from "../src/core/form/Value.bs.js";

function map_n(param) {
  return /* N */0;
}

var dnaV0_01 = DNA$Formform.makeUnsafe([/* U */1]);

var dnaV1_01 = DNA$Formform.makeUnsafe([
      /* M */3,
      /* I */2,
      /* U */1,
      /* N */0
    ]);

var dnaV2_01 = DNA$Formform.makeUnsafe([
      /* N */0,
      /* U */1,
      /* I */2,
      /* M */3,
      /* N */0,
      /* N */0,
      /* I */2,
      /* I */2,
      /* N */0,
      /* U */1,
      /* N */0,
      /* U */1,
      /* N */0,
      /* N */0,
      /* N */0,
      /* N */0
    ]);

var dnaV3_01 = DNA$Formform.makeUnsafe([
      /* N */0,
      /* U */1,
      /* I */2,
      /* M */3,
      /* U */1,
      /* N */0,
      /* M */3,
      /* I */2,
      /* I */2,
      /* M */3,
      /* N */0,
      /* U */1,
      /* M */3,
      /* I */2,
      /* U */1,
      /* N */0,
      /* U */1,
      /* U */1,
      /* M */3,
      /* M */3,
      /* U */1,
      /* I */2,
      /* M */3,
      /* M */3,
      /* M */3,
      /* M */3,
      /* U */1,
      /* U */1,
      /* M */3,
      /* M */3,
      /* U */1,
      /* I */2,
      /* I */2,
      /* M */3,
      /* I */2,
      /* M */3,
      /* M */3,
      /* I */2,
      /* M */3,
      /* I */2,
      /* I */2,
      /* M */3,
      /* I */2,
      /* M */3,
      /* M */3,
      /* I */2,
      /* M */3,
      /* I */2,
      /* M */3,
      /* M */3,
      /* M */3,
      /* M */3,
      /* M */3,
      /* M */3,
      /* M */3,
      /* M */3,
      /* M */3,
      /* M */3,
      /* M */3,
      /* M */3,
      /* M */3,
      /* M */3,
      /* M */3,
      /* I */2
    ]);

Zora.test("Testing VPoint.show", (function (t) {
        t.test("given an empty VPoint", (function (t) {
                var input = [];
                var expected = "[]";
                t.equal(Value$Formform.VPoint.show(input), expected, "should be " + expected);
                var expected$1 = "";
                t.equal(Value$Formform.VPoint.showAsKey(input), expected$1, "should be " + expected$1);
                
              }));
        t.test("given a singleton VPoint", (function (t) {
                var input = [/* N */0];
                var expected = "[N]";
                t.equal(Value$Formform.VPoint.show(input), expected, "should be " + expected);
                var expected$1 = "N";
                t.equal(Value$Formform.VPoint.showAsKey(input), expected$1, "should be " + expected$1);
                
              }));
        t.test("given a VPoint", (function (t) {
                var input = [
                  /* N */0,
                  /* U */1,
                  /* I */2,
                  /* M */3,
                  /* I */2
                ];
                var expected = "[N,U,I,M,I]";
                t.equal(Value$Formform.VPoint.show(input), expected, "should be " + expected);
                var expected$1 = "NUIMI";
                t.equal(Value$Formform.VPoint.showAsKey(input), expected$1, "should be " + expected$1);
                
              }));
        
      }));

Zora.test("Testing VPoint.tFromStr", (function (t) {
        t.test("given an empty string", (function (t) {
                var actual = Value$Formform.VPoint.tFromStr(undefined, "");
                var expected = [];
                t.equal(actual, expected, "should be some empty array");
                
              }));
        t.test("given a const char", (function (t) {
                var actual = Value$Formform.VPoint.tFromStr(undefined, "N");
                var expected = [/* N */0];
                t.equal(actual, expected, "should be some array [N]");
                
              }));
        t.test("given a const string", (function (t) {
                var actual = Value$Formform.VPoint.tFromStr(undefined, "NUIMI");
                var expected = [
                  /* N */0,
                  /* U */1,
                  /* I */2,
                  /* M */3,
                  /* I */2
                ];
                t.equal(actual, expected, "should be some array [N,U,I,M,I]");
                
              }));
        t.test("given an int char", (function (t) {
                var actual = Value$Formform.VPoint.tFromStr(undefined, "0");
                var expected = [/* N */0];
                t.equal(actual, expected, "should be some array [N]");
                
              }));
        t.test("given an int string", (function (t) {
                var actual = Value$Formform.VPoint.tFromStr(undefined, "01232");
                var expected = [
                  /* N */0,
                  /* U */1,
                  /* I */2,
                  /* M */3,
                  /* I */2
                ];
                t.equal(actual, expected, "should be some array [N,U,I,M,I]");
                
              }));
        t.test("given an invalid char", (function (t) {
                var actual = Value$Formform.VPoint.tFromStr(undefined, "O");
                t.equal(actual, undefined, "should be None");
                
              }));
        t.test("given an invalid string", (function (t) {
                var actual = Value$Formform.VPoint.tFromStr(undefined, "M_");
                t.equal(actual, undefined, "should be None");
                
              }));
        
      }));

Zora.test("Testing VSpace.make", (function (t) {
        t.test("given dimension 0", (function (t) {
                var actual = Value$Formform.VSpace.make(undefined, 0);
                var expected = [[/* N */0]];
                t.equal(Value$Formform.VSpace.getPoints(actual), expected, "should be a VSpace of size according to dimension");
                
              }));
        t.test("given dimension 1", (function (t) {
                var actual = Value$Formform.VSpace.make(undefined, 1);
                var expected = [
                  [/* N */0],
                  [/* U */1],
                  [/* I */2],
                  [/* M */3]
                ];
                t.equal(Value$Formform.VSpace.getPoints(actual), expected, "should be a VSpace of size according to dimension");
                
              }));
        t.test("given dimension 2", (function (t) {
                var actual = Value$Formform.VSpace.make(undefined, 2);
                var expected = [
                  [
                    /* N */0,
                    /* N */0
                  ],
                  [
                    /* N */0,
                    /* U */1
                  ],
                  [
                    /* N */0,
                    /* I */2
                  ],
                  [
                    /* N */0,
                    /* M */3
                  ],
                  [
                    /* U */1,
                    /* N */0
                  ],
                  [
                    /* U */1,
                    /* U */1
                  ],
                  [
                    /* U */1,
                    /* I */2
                  ],
                  [
                    /* U */1,
                    /* M */3
                  ],
                  [
                    /* I */2,
                    /* N */0
                  ],
                  [
                    /* I */2,
                    /* U */1
                  ],
                  [
                    /* I */2,
                    /* I */2
                  ],
                  [
                    /* I */2,
                    /* M */3
                  ],
                  [
                    /* M */3,
                    /* N */0
                  ],
                  [
                    /* M */3,
                    /* U */1
                  ],
                  [
                    /* M */3,
                    /* I */2
                  ],
                  [
                    /* M */3,
                    /* M */3
                  ]
                ];
                t.equal(Value$Formform.VSpace.getPoints(actual), expected, "should be a VSpace of size according to dimension");
                
              }));
        
      }));

function listRel(vp) {
  return Belt_Array.reduce(vp, /* N */0, (function (c1, c2) {
                return Calc$Formform.Const.rel(c1, c2);
              }));
}

Zora.test("Testing VSpace.toDNA", (function (t) {
        t.test("given a dim. 0 VSpace", (function (t) {
                var input = Value$Formform.VSpace.make(undefined, 0);
                var actual = Value$Formform.VSpace.toDNA(input, listRel);
                var expected = DNA$Formform.makeUnsafe([/* N */0]);
                t.equal(actual, expected, "should be a DNA " + DNA$Formform.show(undefined, undefined, expected));
                
              }));
        t.test("given a dim. 1 VSpace", (function (t) {
                var input = Value$Formform.VSpace.make(undefined, 1);
                var actual = Value$Formform.VSpace.toDNA(input, listRel);
                var expected = DNA$Formform.makeUnsafe([
                      /* M */3,
                      /* I */2,
                      /* U */1,
                      /* N */0
                    ]);
                t.equal(actual, expected, "should be a DNA " + DNA$Formform.show(undefined, undefined, expected));
                
              }));
        t.test("given a dim. 2 VSpace", (function (t) {
                var input = Value$Formform.VSpace.make(undefined, 2);
                var actual = Value$Formform.VSpace.toDNA(input, listRel);
                var expected = DNA$Formform.makeUnsafe([
                      /* M */3,
                      /* M */3,
                      /* M */3,
                      /* M */3,
                      /* M */3,
                      /* I */2,
                      /* M */3,
                      /* I */2,
                      /* M */3,
                      /* M */3,
                      /* U */1,
                      /* U */1,
                      /* M */3,
                      /* I */2,
                      /* U */1,
                      /* N */0
                    ]);
                t.equal(actual, expected, "should be a DNA " + DNA$Formform.show(undefined, undefined, expected));
                
              }));
        
      }));

Zora.test("Testing VMap.make", (function (t) {
        t.test("given a VSpace", (function (t) {
                var actual = Value$Formform.VMap.make(undefined, 0, map_n);
                var expected = Value$Formform.VMap.makeUnsafe_Cell(/* N */0);
                t.equal(actual, expected, "should be a valid VMap");
                var expected$1 = "<N>";
                t.equal(Value$Formform.VMap.show(undefined, actual), expected$1, "should be " + expected$1);
                
              }));
        t.test("given a VSpace", (function (t) {
                var actual = Value$Formform.VMap.make(undefined, 1, map_n);
                var expected = Value$Formform.VMap.makeUnsafe_Map([
                      [
                        /* N */0,
                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                      ],
                      [
                        /* U */1,
                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                      ],
                      [
                        /* I */2,
                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                      ],
                      [
                        /* M */3,
                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                      ]
                    ]);
                t.equal(actual, expected, "should be a valid VMap");
                var expected$1 = "[N: <N>, U: <N>, I: <N>, M: <N>]";
                t.equal(Value$Formform.VMap.show(undefined, actual), expected$1, "should be " + expected$1);
                
              }));
        t.test("given a VSpace", (function (t) {
                var actual = Value$Formform.VMap.make(undefined, 2, map_n);
                var expected = Value$Formform.VMap.makeUnsafe_Map([
                      [
                        /* N */0,
                        Value$Formform.VMap.makeUnsafe_Map([
                              [
                                /* N */0,
                                Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                              ],
                              [
                                /* U */1,
                                Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                              ],
                              [
                                /* I */2,
                                Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                              ],
                              [
                                /* M */3,
                                Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                              ]
                            ])
                      ],
                      [
                        /* U */1,
                        Value$Formform.VMap.makeUnsafe_Map([
                              [
                                /* N */0,
                                Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                              ],
                              [
                                /* U */1,
                                Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                              ],
                              [
                                /* I */2,
                                Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                              ],
                              [
                                /* M */3,
                                Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                              ]
                            ])
                      ],
                      [
                        /* I */2,
                        Value$Formform.VMap.makeUnsafe_Map([
                              [
                                /* N */0,
                                Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                              ],
                              [
                                /* U */1,
                                Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                              ],
                              [
                                /* I */2,
                                Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                              ],
                              [
                                /* M */3,
                                Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                              ]
                            ])
                      ],
                      [
                        /* M */3,
                        Value$Formform.VMap.makeUnsafe_Map([
                              [
                                /* N */0,
                                Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                              ],
                              [
                                /* U */1,
                                Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                              ],
                              [
                                /* I */2,
                                Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                              ],
                              [
                                /* M */3,
                                Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                              ]
                            ])
                      ]
                    ]);
                t.equal(actual, expected, "should be a valid VMap");
                var expected$1 = "[\n  N: [N: <N>, U: <N>, I: <N>, M: <N>], \n  U: [N: <N>, U: <N>, I: <N>, M: <N>], \n  I: [N: <N>, U: <N>, I: <N>, M: <N>], \n  M: [N: <N>, U: <N>, I: <N>, M: <N>]\n]";
                t.equal(Value$Formform.VMap.show(undefined, actual), expected$1, "should be " + expected$1);
                
              }));
        t.test("given a VSpace", (function (t) {
                var actual = Value$Formform.VMap.make(undefined, 3, map_n);
                var expected = Value$Formform.VMap.makeUnsafe_Map([
                      [
                        /* N */0,
                        Value$Formform.VMap.makeUnsafe_Map([
                              [
                                /* N */0,
                                Value$Formform.VMap.makeUnsafe_Map([
                                      [
                                        /* N */0,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* U */1,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* I */2,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* M */3,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ]
                                    ])
                              ],
                              [
                                /* U */1,
                                Value$Formform.VMap.makeUnsafe_Map([
                                      [
                                        /* N */0,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* U */1,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* I */2,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* M */3,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ]
                                    ])
                              ],
                              [
                                /* I */2,
                                Value$Formform.VMap.makeUnsafe_Map([
                                      [
                                        /* N */0,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* U */1,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* I */2,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* M */3,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ]
                                    ])
                              ],
                              [
                                /* M */3,
                                Value$Formform.VMap.makeUnsafe_Map([
                                      [
                                        /* N */0,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* U */1,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* I */2,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* M */3,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ]
                                    ])
                              ]
                            ])
                      ],
                      [
                        /* U */1,
                        Value$Formform.VMap.makeUnsafe_Map([
                              [
                                /* N */0,
                                Value$Formform.VMap.makeUnsafe_Map([
                                      [
                                        /* N */0,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* U */1,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* I */2,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* M */3,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ]
                                    ])
                              ],
                              [
                                /* U */1,
                                Value$Formform.VMap.makeUnsafe_Map([
                                      [
                                        /* N */0,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* U */1,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* I */2,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* M */3,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ]
                                    ])
                              ],
                              [
                                /* I */2,
                                Value$Formform.VMap.makeUnsafe_Map([
                                      [
                                        /* N */0,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* U */1,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* I */2,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* M */3,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ]
                                    ])
                              ],
                              [
                                /* M */3,
                                Value$Formform.VMap.makeUnsafe_Map([
                                      [
                                        /* N */0,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* U */1,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* I */2,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* M */3,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ]
                                    ])
                              ]
                            ])
                      ],
                      [
                        /* I */2,
                        Value$Formform.VMap.makeUnsafe_Map([
                              [
                                /* N */0,
                                Value$Formform.VMap.makeUnsafe_Map([
                                      [
                                        /* N */0,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* U */1,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* I */2,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* M */3,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ]
                                    ])
                              ],
                              [
                                /* U */1,
                                Value$Formform.VMap.makeUnsafe_Map([
                                      [
                                        /* N */0,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* U */1,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* I */2,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* M */3,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ]
                                    ])
                              ],
                              [
                                /* I */2,
                                Value$Formform.VMap.makeUnsafe_Map([
                                      [
                                        /* N */0,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* U */1,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* I */2,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* M */3,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ]
                                    ])
                              ],
                              [
                                /* M */3,
                                Value$Formform.VMap.makeUnsafe_Map([
                                      [
                                        /* N */0,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* U */1,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* I */2,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* M */3,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ]
                                    ])
                              ]
                            ])
                      ],
                      [
                        /* M */3,
                        Value$Formform.VMap.makeUnsafe_Map([
                              [
                                /* N */0,
                                Value$Formform.VMap.makeUnsafe_Map([
                                      [
                                        /* N */0,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* U */1,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* I */2,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* M */3,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ]
                                    ])
                              ],
                              [
                                /* U */1,
                                Value$Formform.VMap.makeUnsafe_Map([
                                      [
                                        /* N */0,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* U */1,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* I */2,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* M */3,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ]
                                    ])
                              ],
                              [
                                /* I */2,
                                Value$Formform.VMap.makeUnsafe_Map([
                                      [
                                        /* N */0,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* U */1,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* I */2,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* M */3,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ]
                                    ])
                              ],
                              [
                                /* M */3,
                                Value$Formform.VMap.makeUnsafe_Map([
                                      [
                                        /* N */0,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* U */1,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* I */2,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ],
                                      [
                                        /* M */3,
                                        Value$Formform.VMap.makeUnsafe_Cell(/* N */0)
                                      ]
                                    ])
                              ]
                            ])
                      ]
                    ]);
                t.equal(actual, expected, "should be a valid VMap");
                var expected$1 = "[\n  N: [\n    N: [N: <N>, U: <N>, I: <N>, M: <N>], \n    U: [N: <N>, U: <N>, I: <N>, M: <N>], \n    I: [N: <N>, U: <N>, I: <N>, M: <N>], \n    M: [N: <N>, U: <N>, I: <N>, M: <N>]\n  ], \n  U: [\n    N: [N: <N>, U: <N>, I: <N>, M: <N>], \n    U: [N: <N>, U: <N>, I: <N>, M: <N>], \n    I: [N: <N>, U: <N>, I: <N>, M: <N>], \n    M: [N: <N>, U: <N>, I: <N>, M: <N>]\n  ], \n  I: [\n    N: [N: <N>, U: <N>, I: <N>, M: <N>], \n    U: [N: <N>, U: <N>, I: <N>, M: <N>], \n    I: [N: <N>, U: <N>, I: <N>, M: <N>], \n    M: [N: <N>, U: <N>, I: <N>, M: <N>]\n  ], \n  M: [\n    N: [N: <N>, U: <N>, I: <N>, M: <N>], \n    U: [N: <N>, U: <N>, I: <N>, M: <N>], \n    I: [N: <N>, U: <N>, I: <N>, M: <N>], \n    M: [N: <N>, U: <N>, I: <N>, M: <N>]\n  ]\n]";
                t.equal(Value$Formform.VMap.show(undefined, actual), expected$1, "should be " + expected$1);
                
              }));
        
      }));

Zora.test("Testing VMap.fromDNA", (function (t) {
        t.test("given a DNA", (function (t) {
                var actual = Value$Formform.VMap.fromDNA(dnaV0_01);
                var expected = "<U>";
                t.equal(Value$Formform.VMap.show(undefined, actual), expected, "should be " + expected);
                
              }));
        t.test("given a DNA", (function (t) {
                var actual = Value$Formform.VMap.fromDNA(dnaV1_01);
                var expected = "[N: <N>, U: <U>, I: <I>, M: <M>]";
                t.equal(Value$Formform.VMap.show(undefined, actual), expected, "should be " + expected);
                
              }));
        t.test("given a DNA", (function (t) {
                var actual = Value$Formform.VMap.fromDNA(dnaV2_01);
                var expected = "[\n  N: [N: <N>, U: <N>, I: <N>, M: <N>], \n  U: [N: <U>, U: <N>, I: <U>, M: <N>], \n  I: [N: <I>, U: <I>, I: <N>, M: <N>], \n  M: [N: <M>, U: <I>, I: <U>, M: <N>]\n]";
                t.equal(Value$Formform.VMap.show(undefined, actual), expected, "should be " + expected);
                
              }));
        t.test("given a DNA", (function (t) {
                var actual = Value$Formform.VMap.fromDNA(dnaV3_01);
                var expected = "[\n  N: [\n    N: [N: <I>, U: <M>, I: <M>, M: <M>], \n    U: [N: <M>, U: <M>, I: <M>, M: <M>], \n    I: [N: <M>, U: <M>, I: <M>, M: <M>], \n    M: [N: <M>, U: <M>, I: <M>, M: <M>]\n  ], \n  U: [\n    N: [N: <I>, U: <M>, I: <I>, M: <M>], \n    U: [N: <M>, U: <I>, I: <M>, M: <I>], \n    I: [N: <I>, U: <M>, I: <I>, M: <M>], \n    M: [N: <M>, U: <I>, I: <M>, M: <I>]\n  ], \n  I: [\n    N: [N: <I>, U: <U>, I: <M>, M: <M>], \n    U: [N: <U>, U: <U>, I: <M>, M: <M>], \n    I: [N: <M>, U: <M>, I: <I>, M: <U>], \n    M: [N: <M>, U: <M>, I: <U>, M: <U>]\n  ], \n  M: [\n    N: [N: <N>, U: <U>, I: <I>, M: <M>], \n    U: [N: <U>, U: <N>, I: <M>, M: <I>], \n    I: [N: <I>, U: <M>, I: <N>, M: <U>], \n    M: [N: <M>, U: <I>, I: <U>, M: <N>]\n  ]\n]";
                t.equal(Value$Formform.VMap.show(undefined, actual), expected, "should be " + expected);
                
              }));
        
      }));

Zora.test("Testing VDict.make", (function (t) {
        t.test("given a vspace", (function (t) {
                var actual = Value$Formform.VDict.make(undefined, 0, map_n);
                var expected = Value$Formform.VDict.fromDictUnsafe(Js_dict.fromArray([[
                            "N",
                            /* N */0
                          ]]));
                t.equal(actual, expected, "should be a vdict");
                t.equal(Value$Formform.VDict.show(actual), "VSpace -> DNA\n-------------\nN -> N", "should be a string representation of the vdict");
                
              }));
        t.test("given a vspace", (function (t) {
                var actual = Value$Formform.VDict.make(undefined, 1, map_n);
                var expected = Value$Formform.VDict.fromDictUnsafe(Js_dict.fromArray([
                          [
                            "N",
                            /* N */0
                          ],
                          [
                            "U",
                            /* N */0
                          ],
                          [
                            "I",
                            /* N */0
                          ],
                          [
                            "M",
                            /* N */0
                          ]
                        ]));
                t.equal(actual, expected, "should be a vdict");
                t.equal(Value$Formform.VDict.show(actual), "VSpace -> DNA\n-------------\nN -> N\nU -> N\nI -> N\nM -> N", "should be a string representation of the vdict");
                
              }));
        t.test("given a vspace", (function (t) {
                var actual = Value$Formform.VDict.make(undefined, 2, map_n);
                var expected = Value$Formform.VDict.fromDictUnsafe(Js_dict.fromArray([
                          [
                            "NN",
                            /* N */0
                          ],
                          [
                            "NU",
                            /* N */0
                          ],
                          [
                            "NI",
                            /* N */0
                          ],
                          [
                            "NM",
                            /* N */0
                          ],
                          [
                            "UN",
                            /* N */0
                          ],
                          [
                            "UU",
                            /* N */0
                          ],
                          [
                            "UI",
                            /* N */0
                          ],
                          [
                            "UM",
                            /* N */0
                          ],
                          [
                            "IN",
                            /* N */0
                          ],
                          [
                            "IU",
                            /* N */0
                          ],
                          [
                            "II",
                            /* N */0
                          ],
                          [
                            "IM",
                            /* N */0
                          ],
                          [
                            "MN",
                            /* N */0
                          ],
                          [
                            "MU",
                            /* N */0
                          ],
                          [
                            "MI",
                            /* N */0
                          ],
                          [
                            "MM",
                            /* N */0
                          ]
                        ]));
                t.equal(actual, expected, "should be a vdict");
                t.equal(Value$Formform.VDict.show(actual), "VSpace -> DNA\n-------------\nNN -> N\nNU -> N\nNI -> N\nNM -> N\nUN -> N\nUU -> N\nUI -> N\nUM -> N\nIN -> N\nIU -> N\nII -> N\nIM -> N\nMN -> N\nMU -> N\nMI -> N\nMM -> N", "should be a string representation of the vdict");
                
              }));
        
      }));

Zora.test("Testing VDict.fromDNA", (function (t) {
        t.test("given a vspace", (function (t) {
                var actual = Value$Formform.VDict.fromDNA(dnaV0_01);
                var expected = Value$Formform.VDict.fromDictUnsafe(Js_dict.fromArray([[
                            "N",
                            /* U */1
                          ]]));
                t.equal(actual, expected, "should be a vdict");
                
              }));
        t.test("given a vspace", (function (t) {
                var actual = Value$Formform.VDict.fromDNA(dnaV1_01);
                var expected = Value$Formform.VDict.fromDictUnsafe(Js_dict.fromArray([
                          [
                            "N",
                            /* N */0
                          ],
                          [
                            "U",
                            /* U */1
                          ],
                          [
                            "I",
                            /* I */2
                          ],
                          [
                            "M",
                            /* M */3
                          ]
                        ]));
                t.equal(actual, expected, "should be a vdict");
                
              }));
        t.test("given a vspace", (function (t) {
                var actual = Value$Formform.VDict.fromDNA(dnaV2_01);
                var expected = Value$Formform.VDict.fromDictUnsafe(Js_dict.fromArray([
                          [
                            "NN",
                            /* N */0
                          ],
                          [
                            "NU",
                            /* N */0
                          ],
                          [
                            "NI",
                            /* N */0
                          ],
                          [
                            "NM",
                            /* N */0
                          ],
                          [
                            "UN",
                            /* U */1
                          ],
                          [
                            "UU",
                            /* N */0
                          ],
                          [
                            "UI",
                            /* U */1
                          ],
                          [
                            "UM",
                            /* N */0
                          ],
                          [
                            "IN",
                            /* I */2
                          ],
                          [
                            "IU",
                            /* I */2
                          ],
                          [
                            "II",
                            /* N */0
                          ],
                          [
                            "IM",
                            /* N */0
                          ],
                          [
                            "MN",
                            /* M */3
                          ],
                          [
                            "MU",
                            /* I */2
                          ],
                          [
                            "MI",
                            /* U */1
                          ],
                          [
                            "MM",
                            /* N */0
                          ]
                        ]));
                t.equal(actual, expected, "should be a vdict");
                
              }));
        
      }));

export {
  map_n ,
  dnaV0_01 ,
  dnaV1_01 ,
  dnaV2_01 ,
  dnaV3_01 ,
  listRel ,
  
}
/* dnaV0_01 Not a pure module */
